# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

set_seed <- function(seed) {
    invisible(.Call('_dli55_set_seed', PACKAGE = 'dli55', seed))
}

predict_cpp <- function(n, nsr, reps, V) {
    .Call('_dli55_predict_cpp', PACKAGE = 'dli55', n, nsr, reps, V)
}

pcd2_loop <- function(SSii, nsr, SCii, comm, V, nsp_pool, verbose) {
    .Call('_dli55_pcd2_loop', PACKAGE = 'dli55', SSii, nsr, SCii, comm, V, nsp_pool, verbose)
}

